FROM node:alpine

USER node

WORKDIR '/app'

COPY --chown=node:node package.json .

RUN npm install

RUN mkdir ./node_modules/.cache; chown -R node:node ./node_modules

COPY --chown=node:node ./ ./

CMD [ "npm", "run", "start" ]
