version: '3'
services: 
  web:
    image: bytejumper/frontend:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ~/frontend:/app
  tests:
    image: bytejumper/frontend:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ~/frontend:/app
    command: [ "npm", "run", "test" ]